// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9rk1lA4IFTa_qjl8QpNcPy3x-74YjC8',
    appId: '1:982826830444:web:693d8d194fcc48a030a649',
    messagingSenderId: '982826830444',
    projectId: 'flight-tracker-ios',
    authDomain: 'flight-tracker-ios.firebaseapp.com',
    storageBucket: 'flight-tracker-ios.appspot.com',
    measurementId: 'G-58CCH184GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb8eY867OVu1ngW1YaM_fxrCInH-RvL2M',
    appId: '1:982826830444:android:159648f4fed7897e30a649',
    messagingSenderId: '982826830444',
    projectId: 'flight-tracker-ios',
    storageBucket: 'flight-tracker-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIdVUlKxWd9jnni0VVDzDCOr6KhsqoO0s',
    appId: '1:982826830444:ios:bc956d596e85189c30a649',
    messagingSenderId: '982826830444',
    projectId: 'flight-tracker-ios',
    storageBucket: 'flight-tracker-ios.appspot.com',
    iosClientId: '982826830444-k7t1bh4t1dl4euu7fogo2nbgjut84q6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileToMobileWebrtc',
  );
}
